-- DROP TABLE NODE;

CREATE TABLE IF NOT EXISTS NODE (
    id INTEGER generated by default as identity primary key,
    node_id VARCHAR(255) UNIQUE not null,
    name VARCHAR(255) not null,
    description VARCHAR(255) not null,
    memo VARCHAR(255) not null,
    type VARCHAR(255) not null,
    parent_group_name VARCHAR(255) not null,
    parent_group_id VARCHAR(255) not null,
    parent_name VARCHAR(255) not null
);